#!/bin/bash

# In order to cross-compile node for Android using NDK, run:
#   source android-configure <path_to_ndk> [arch]
#
# By running android-configure with source, will allow environment variables to
# be persistent in current session. This is useful for installing native node
# modules with npm. Also, don't forget to set the arch in npm config using
# 'npm config set arch=<arch>'


if [ -z "$2" ]; then
    ARCH=arm64
else
    ARCH="$2"
fi

CC_VER="4.9"
case $ARCH in
    arm64)
        DEST_CPU="$ARCH"
        SUFFIX="aarch64-linux-android"
        TOOLCHAIN_NAME="$SUFFIX"
        ;;
    arm)
        DEST_CPU="$ARCH"
        SUFFIX="$ARCH-linux-androideabi"
        TOOLCHAIN_NAME="$SUFFIX"
        ;;
    x86)
        DEST_CPU="ia32"
        SUFFIX="i686-linux-android"
        TOOLCHAIN_NAME="$ARCH"
        ;;
    x86_64)
        DEST_CPU="ia32"
        SUFFIX="$ARCH-linux-android"
        TOOLCHAIN_NAME="$ARCH"
        ;;
    *)
        echo "Unsupported architecture provided: $ARCH"
        exit 1
        ;;
esac

export TOOLCHAIN="$MLSDK"

export PATH=$TOOLCHAIN/bin:$PATH
export AR=$TOOLCHAIN/bin/$SUFFIX-ar
export CC="$TOOLCHAIN/bin/$SUFFIX-clang -I$MLSDK/sysroot/usr/include/c++/v1 -I$MLSDK/sysroot/usr/include -I$MLSDK/include -Ideps/cares/include -DLUMIN=1 --sysroot=$MLSDK/sysroot/"
export CXX="$TOOLCHAIN/bin/$SUFFIX-clang++ -I$MLSDK/sysroot/usr/include/c__/v1 -I$MLSDK/sysroot/usr/include -I$MLSDK/include -Ideps/cares/include -DLUMIN=1 --sysroot=$MLSDK/sysroot/"
export LINK="$TOOLCHAIN/bin/$SUFFIX-clang++ --sysroot=$MLSDK/sysroot/ -L$MLSDK/sysroot/usr/lib -L$MLSDK/sysroot/usr/lib/aarch64-linux-android/28 -L$MLSDK/tools/toolchains/lib64/clang/3.8.275480/lib/linux -L$MLSDK/lib/lib64 -lc -lc++_static -lc++_shared"
export AR_host=ar
export CC_host=gcc
export CXX_host=g++
export LINK_host=g++

GYP_DEFINES="target_arch=$ARCH"
GYP_DEFINES+=" v8_target_arch=$ARCH"
# GYP_DEFINES+=" android_target_arch=$ARCH"
GYP_DEFINES+=" host_os=linux OS=android"
export GYP_DEFINES

if [ -f "configure" ]; then
    ./configure \
        --dest-cpu=$DEST_CPU \
        --dest-os=linux \
        --without-intl \
        --cross-compiling \
        --enable-static
fi
